  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job has completed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token
          publish_dir: ./dist  # Path to the dist folder
          publish_branch: gh-pages  # The branch to deploy to
          user_name: 'GitHub Actions'  # User for the commits
          user_email: 'actions@github.com'  # User email for the commits
