name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]  # Test with different Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 🚫 Add .nojekyll to disable Jekyll on GitHub Pages
        run: touch dist/.nojekyll
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build  # This will generate the dist folder

      - name: Verify dist output
        run: ls -la dist  # Verifying that dist folder is generated

      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-node-${{ matrix.node-version }}
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build  # Make sure build job runs first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
          publish_dir: ./dist  # Path to the dist folder
          publish_branch: gh-pages  # Deploy to the gh-pages branch
          user_name: 'GitHub Actions'  # GitHub username for commits
          user_email: 'actions@github.com'  # GitHub email for commits

  check:
    name: Run checks (Astro, ESLint, Prettier)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint/type/style checks
        run: npm run check
